### ISSUE TITLE
-бизнес срарки

### ISSUE THREAD

**Issue by KittenPro** [TheAcelot/srolette-srawl-leak#3]
#ZаНаших

**Comment by TheAcelot** [comment]
- Я УКРАИНСКИЙ ВОЕННЫЙ КОРАБЛЬ ПРЕДЛАГАЮ СЛОЖИТЬ ОРУЖИЕ И СДАТЬСЯ
- УКРАИНСКИЙ ВОЕННЫЙ КОРАБЛЬ ИДИ НАХ*Й
